// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFO6pz4hiHlfU_4s-t_mu3u5ensaYFvxU',
    appId: '1:244771868814:web:a406bbbde5d949bf4e79df',
    messagingSenderId: '244771868814',
    projectId: 'eliam-1',
    authDomain: 'eliam-1.firebaseapp.com',
    storageBucket: 'eliam-1.appspot.com',
    measurementId: 'G-LY103377NB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6sBStTWnpLtsPun0sttZXJkwmGZ32zUM',
    appId: '1:244771868814:android:8b577b4c77354c524e79df',
    messagingSenderId: '244771868814',
    projectId: 'eliam-1',
    storageBucket: 'eliam-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcbVFDgT4fsUFGS7Dv1_3DO7rDMnmgPu8',
    appId: '1:244771868814:ios:045fab62240de8624e79df',
    messagingSenderId: '244771868814',
    projectId: 'eliam-1',
    storageBucket: 'eliam-1.appspot.com',
    iosBundleId: 'com.eliam.furnitur',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcbVFDgT4fsUFGS7Dv1_3DO7rDMnmgPu8',
    appId: '1:244771868814:ios:045fab62240de8624e79df',
    messagingSenderId: '244771868814',
    projectId: 'eliam-1',
    storageBucket: 'eliam-1.appspot.com',
    iosBundleId: 'com.eliam.furnitur',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFO6pz4hiHlfU_4s-t_mu3u5ensaYFvxU',
    appId: '1:244771868814:web:2e46b9d8cd6b2a6f4e79df',
    messagingSenderId: '244771868814',
    projectId: 'eliam-1',
    authDomain: 'eliam-1.firebaseapp.com',
    storageBucket: 'eliam-1.appspot.com',
    measurementId: 'G-7HJKR1L71V',
  );

}